[project]
name = "progress-timer"
version = "0.1.0"
description = "A minimalist timer that also tracks the progress of your task."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.ruff]
line-length = 120

[dependency-groups]
dev = [
    "ruff>=0.9.7",
]
